// Code generated by MockGen. DO NOT EDIT.
// Source: internal/profiles/usecase.go

// Package mock_profiles is a generated GoMock package.
package mock_profiles

import (
	context "context"
	models "cyansnbrst/profiles-service/internal/models"
	kafka "cyansnbrst/profiles-service/pkg/kafka"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	kafka0 "github.com/segmentio/kafka-go"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockUseCase) CreateProfile(uid, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", uid, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockUseCaseMockRecorder) CreateProfile(uid, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockUseCase)(nil).CreateProfile), uid, name)
}

// Get mocks base method.
func (m *MockUseCase) Get(uid string) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", uid)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUseCaseMockRecorder) Get(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUseCase)(nil).Get), uid)
}

// SendToKafka mocks base method.
func (m *MockUseCase) SendToKafka(ctx context.Context, key string, message kafka.KafkaMessage, writer *kafka0.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToKafka", ctx, key, message, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToKafka indicates an expected call of SendToKafka.
func (mr *MockUseCaseMockRecorder) SendToKafka(ctx, key, message, writer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToKafka", reflect.TypeOf((*MockUseCase)(nil).SendToKafka), ctx, key, message, writer)
}

// Update mocks base method.
func (m *MockUseCase) Update(uid string, location *string, interests []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", uid, location, interests)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUseCaseMockRecorder) Update(uid, location, interests interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), uid, location, interests)
}
