// Code generated by MockGen. DO NOT EDIT.
// Source: internal/recommendations/redis_repository.go

// Package mock_recommendations is a generated GoMock package.
package mock_recommendations

import (
	models "cyansnbrst/recommendations-service/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRedisRepository is a mock of RedisRepository interface.
type MockRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryMockRecorder
}

// MockRedisRepositoryMockRecorder is the mock recorder for MockRedisRepository.
type MockRedisRepositoryMockRecorder struct {
	mock *MockRedisRepository
}

// NewMockRedisRepository creates a new mock instance.
func NewMockRedisRepository(ctrl *gomock.Controller) *MockRedisRepository {
	mock := &MockRedisRepository{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepository) EXPECT() *MockRedisRepositoryMockRecorder {
	return m.recorder
}

// GetRecommendations mocks base method.
func (m *MockRedisRepository) GetRecommendations(key string) ([]models.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendations", key)
	ret0, _ := ret[0].([]models.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendations indicates an expected call of GetRecommendations.
func (mr *MockRedisRepositoryMockRecorder) GetRecommendations(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendations", reflect.TypeOf((*MockRedisRepository)(nil).GetRecommendations), key)
}

// SetRecommendations mocks base method.
func (m *MockRedisRepository) SetRecommendations(key string, recommendations []models.Recommendation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecommendations", key, recommendations)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecommendations indicates an expected call of SetRecommendations.
func (mr *MockRedisRepositoryMockRecorder) SetRecommendations(key, recommendations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecommendations", reflect.TypeOf((*MockRedisRepository)(nil).SetRecommendations), key, recommendations)
}
